### ISSUE TITLE
Provide log output box for player logging

### ISSUE THREAD

**Issue by keriwarr** [KeriWarr/luminescence#2]
Not sure how `console.log`'s from player code will have their output captured... Need to figure this out.

**Comment by justinthec** [comment]
Maybe we can provide a separate console called `lumconsole` and have them log on that object instead where we can easily display their debugging outputs on screen.

**Comment by justinthec** [comment]
OR if we're feeling super hacky we can actually just override the console.log method to capture their outputs like so 

```
var oldLogFunc = console.log;
console.log = function (msg) {
    outputMessages.push(msg);
    oldLogFunc.call(console, msg);
};
```

That will retain old console log functionality but we can store a copy of their messages.

**EDIT:** fixed the `oldLogFunc(msg);` line to call the function on the console object `oldLogFunc.call(console, msg);`
